### ISSUE TITLE
Extract CSS while server rendering

### ISSUE THREAD

**Issue by mbohgard** [forsigner/fower#17]
With styled-components if you load a site in Next.js for ex and have it setup correctly, the page will look correct even with JavaScript disabled. Can we get something like that in Fower, is it planned?

**Comment by forsigner** [comment]
Right now I'm focused on some new features for fower，May be I will support to Extract CSS  few months later, and wellcome to some PR.

**Comment by mbohgard** [comment]
I'll see what I can do. Thank you for your work on Fower!
