### ISSUE TITLE
vue 项目 Responsive 样式， 大的Postfix 会被小的覆盖

### ISSUE THREAD

**Issue by iwiiiwi** [forsigner/fower#19]
fower 版本  1.30.0

问题：
1. 官网的那个 响应式样例能够正常生效， 但是在自己的vue项目中永远是小尺寸的设置生效。
2. 同一个尺寸的@media 样式会出现多个

本地项目样式截图：

![image](https://user-images.githubusercontent.com/16189001/124414077-8911d180-dd84-11eb-863e-6541876ef4d4.png)

**Comment by iwiiiwi** [comment]
项目打包编译出来以后样式就正常了。 只是在开发模式有问题

**Comment by forsigner** [comment]
@iwiiiwi  开发模式因为需要实现 hot reload，导致了这个问题，我还要研究一下这个怎么解决

**Comment by forsigner** [comment]
开发模式时，这个问题暂时只能靠刷新解决
