### ISSUE TITLE
Could not find a declaration file for module '@fower/react-native'

### ISSUE THREAD

**Issue by sgaloux** [forsigner/fower#2]
First of all, thank you for this great package :)

When trying to use the @fower/react-native package, i get an declaration missing error with the @fower/react-native types : 

![image](https://user-images.githubusercontent.com/173028/115949903-5ae85980-a4d8-11eb-9bd1-dc0c5c48cfdd.png)

In the package.json of the pusblished package, i notice the typings is pointing on an missing file... 

![image](https://user-images.githubusercontent.com/173028/115950047-2f19a380-a4d9-11eb-9a83-1eeed2861fe1.png)

![image](https://user-images.githubusercontent.com/173028/115950034-1e692d80-a4d9-11eb-9a11-9b8505e54779.png)

The typing **types/index.d.ts** is missing (seems to be ignored on publish), or located in the wrong folder **dist/**

Thank you for your help.

**Comment by forsigner** [comment]
@sgaloux Thank for  bug feedback, I fixed it in latest version v1.3.0, please check it~
