### ISSUE TITLE
not work on taro 3.3.0

### ISSUE THREAD

**Issue by xing-ou** [forsigner/fower#22]
![image](https://user-images.githubusercontent.com/13159955/125779853-1e611764-586c-42d8-8e42-3a8077a05ebc.png)

**Comment by forsigner** [comment]
有没有更多报错信息，我这边复现不了

**Comment by xing-ou** [comment]
chrome没问题，h5 safari 或者ios上就报这个,我就用的demo工程

**Comment by whitegerry** [comment]
ios 不支持前后断言正则，打包后搜一下断言正则，比如打包小程序后搜 `?<=_`，在 vendor.js 里面删除包含 `?<=_` 的这个函数可以临时解决。

**Comment by forsigner** [comment]
这个我也发现了，我今天改一下

**Comment by whitegerry** [comment]
测试已ok。
