### ISSUE TITLE
嵌套样式冲突

### ISSUE THREAD

**Issue by twinh** [forsigner/fower#29]
如下代码，第一个 `Box`  生成了 CSS `.color-deeppink`，内容为空，导致第二个没有样式。

考虑生成类时把子元素也加上？例如生成 `span-color-deeppink` ?

```js
<div>
  <Box
    css={{
      span: {
        color: 'deeppink',
      },
    }}
  >
    <span>Hi, Fower!</span>
  </Box>
  
  <Box color="deeppink">
    粉色
  </Box>
</div>
```

![image](https://user-images.githubusercontent.com/594436/144349773-895a5b0f-3d2e-4c4a-906e-d77733176f2d.png)

**Comment by forsigner** [comment]
@twinh fixed in new version v1.59.0
