### ISSUE TITLE
允许自定义 css 属性的名称

### ISSUE THREAD

**Issue by twinh** [forsigner/fower#31]
我们的项目原来使用 `emotion`，现在加入了 `fower`。

在 `emotion` 中，所有组件的 `css` (https://emotion.sh/docs/css-prop) 属性会被转换为 `className`。所以 `Box` 组件的 `css` 属性也会被转换，导致 `Box` 的样式失效。

为了解决这个问题，希望 `fower` 能够自定义 `css` 属性的名称，例如可以通过 `setConfig` 更改为 `sx`。

`sx` 在实际中也有很多类库在使用，例如

- https://theme-ui.com/sx-prop/
- https://mui.com/zh/system/the-sx-prop/
- https://primer.style/react/overriding-styles 
- https://chakra-ui.com/docs/features/the-sx-prop

长远的看，例如 v2 版，还可以考虑将 `css` 改为 `sx`，`sx` 表示动态生成的样式。

**Comment by forsigner** [comment]
恩 自定义属性今天晚上我一下，要不要改成 sx，这个我先看看哈

**Comment by forsigner** [comment]
之所以用 css 属性，之前也是借鉴了 emotion。

**Comment by forsigner** [comment]
v1.61.0, 支持 `objectPropKeys` 配置，用法如下(暂时没文档)：
```js
// 默认是 objectPropKeys: ['css']，可以自定义

// 同时支持 css, sx
setConfig({
  objectPropKeys: ['css', 'sx'],
});

// 覆盖默认，只支持 sx
setConfig({
  objectPropKeys: ['sx'],
});
```

**Comment by twinh** [comment]
谢谢，我在使用中遇到两个问题

1. 自定义 `objectPropKeys` 后，`css` 方法失效

```
import {css, setConfig} from '@fower/core';

setConfig({
  objectPropKeys: ['sx'],
});

// 预期输出 toRight，但是会输出空
console.log(css({toRight: true}));
```

定位到是 https://github.com/forsigner/fower/blob/master/packages/core/src/css.ts#L12 `argsToProps` 返回了 `{css: xx}` 对象，但是 `Parser` 解析时是判断 `sx` 键名，所以失效了，需要请你看下怎么调整好。

2. 单独使用 '@fower/core' 类库，缺少 `objectPropKeys` 默认配置，导致 `css` 方法失效。
已经提交 https://github.com/forsigner/fower/pull/32/files

**Comment by forsigner** [comment]
确实放在 store 会更好，发了新版 v1.62.0

**Comment by twinh** [comment]
2. 确认已生效

**Comment by forsigner** [comment]
1. fixed in new version v1.62.1

**Comment by twinh** [comment]
1. 已解决，多了个调试语句 pr 了哈
