### ISSUE TITLE
@fower/taro的 Switch 组件 color样式在微信小程序无法覆盖

### ISSUE THREAD

**Issue by lili-an** [forsigner/fower#35]
<Switch color='#FF6F02' checked />
这个组件color样式无法覆盖 表现还是原始的颜色
应该是color属性和原始组件的color属性冲突导致的

**Comment by xdoer** [comment]
@lili-an 用 excludedProps 处理一下即可
```tsx
<Switch color="#fcd423" excludedProps={['color']} />
```

**Comment by forsigner** [comment]
@xdoer 的方案是可以的，暂时文档没写

**Comment by lili-an** [comment]
@xdoer  方案可行👍 tks
