### ISSUE TITLE
Taro H5 shadow原子不生效

### ISSUE THREAD

**Issue by tourze** [forsigner/fower#37]
![image](https://user-images.githubusercontent.com/13899502/152963259-2fbdc6de-317e-443e-9303-8024161c3ea8.png)

![image](https://user-images.githubusercontent.com/13899502/152963305-5823be12-85d4-4e0d-8e08-27773772c263.png)

fower版本：1.65.0

**Comment by forsigner** [comment]
不好意思，我这段时间比较忙，非react相关问题要晚点有时间才会处理

**Comment by forsigner** [comment]
@tourze 不过欢迎PR
