### ISSUE TITLE
Svelte Rollup waiting for changes forever

### ISSUE THREAD

**Issue by salahcgp** [forsigner/fower#39]
I have added the fowerSveltePreprocess in rollup.config.js, but svelte goes to the waiting mode [ waiting for changes... ] and doesn't respond. I am using:
"@fower/svelte-preprocess": "^1.66.0" and  "svelte": "^3.0.0"

plugins: [
    svelte({
      compilerOptions: {
        // enable run-time checks when not in production
        dev: !production,
      },
      preprocess: fowerSveltePreprocess(),
    }),

**Comment by forsigner** [comment]
Sorry, I am not a svelte user and not familiar with svelte, I will handle this problem when I am not busy, and welcome to some PR for svelte related bugs
