### ISSUE TITLE
Remax: @fower/remax的ts类型问题

### ISSUE THREAD

**Issue by NiuGuohui** [forsigner/fower#41]
@fower/remax下的View、Text等控件没有代码提示，比如toCenterY toCenterX fontBold等基础Props

**Comment by forsigner** [comment]
Fixed in v1.67.0

**Comment by NiuGuohui** [comment]
fower在有了类型提示后结合TS很好用，很爽，不过遗憾的是在remax小程序平台没办法像linaria一样编译成css文件，也无法使用pseudo😭

**Comment by forsigner** [comment]
1. 小程序本来就没办法使用 pseudo 吧
2. 其实没必要编译成 css，纯css会失去很多 js 特性
