### ISSUE TITLE
bug : taro小程序开发中 ，高度和宽度的自定义属性值与预设属性的表现不一致  

### ISSUE THREAD

**Issue by Visualizeit** [forsigner/fower#6]
taro-cli版本：3.2.8  

代码    
![image](https://user-images.githubusercontent.com/61679509/117971708-cf3a4e00-b35c-11eb-9a6a-5440c8e86f40.png)

实际表现
![image](https://user-images.githubusercontent.com/61679509/117971728-d3ff0200-b35c-11eb-8939-65235845434c.png)

**Comment by forsigner** [comment]
这不是bug，因为 taro 默认的 designWidth 是 750，小程序使用的单位是 rpx，在 fower中所有数值的单位都是 rpx, 例如 `w-100` 对标的是 `width: 100rpx`, 也就是 `width: 50px`, 如果用 `w-100px`，因为声明了单位，那就是强制生成 `width: 100px`

**Comment by forsigner** [comment]
举个例子，在taro中，你要设置字体大小为平时web开发中的 16px 时，如果样taro自带的样式写法，你应该要写 `{font-size: 32px}`, 同理，用fower写法，你是写 `text-32`，需要要声明单位，当然你可以修改 designWidth 为 375，那 `text-16` 就是平时理解的 16px 大小

**Comment by Visualizeit** [comment]
谢谢回复，是我大意了
